version: "2"
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
  - "sublime"
  - "xcode"
  - "hidden/.bin/git-completion.bash"
  - "hidden/.bin/Sourcery.app"
  - "hidden/.bin/src/clock"
